### PR TITLE
fix: fixed vuln

### PR DESCRIPTION
**Pull request by ujjwal-kr**

### CODE REVIEW

**Review by PhantomKnight287 — APPROVED** [review]

**Review by PhantomKnight287 — CHANGES_REQUESTED** [review]
It looks like you just changed, Package-lock.json. But you should have changed Package.json too

**Comment by ujjwal-kr** [comment]
should I upgrade the nextjs version?
and what version should i upgrade to?

**Comment by PhantomKnight287** [comment]
You can take a look at security advisory [here](https://github.com/vercel/next.js/security/advisories/GHSA-25mp-g6fv-mqxx). You should upgrade it to  >12.0.05

**Comment by ujjwal-kr** [comment]
pushing shortly

**Pull request merged**
