### PR TITLE
Added some CSS for btn class

### PR DESCRIPTION
**Pull request by Skyhero-admin**
Added some scale CSS for button hover and button click
Peek 2021-11-03 12-52

### CODE REVIEW

**Comment by ujjwal-kr** [comment]
cool! 
acknowledged, waiting for review
cc: @PhantomKnight287

**Comment by ujjwal-kr** [comment]
good work with the gif demonstration btw 🔥

**Review by PhantomKnight287 — COMMENTED** [review]
Review Successful

**Comment by ujjwal-kr** [comment]
thanks for the PR!

**Pull request merged**
